### PR TITLE
#84: Added Exasol SQL statement builder

### LINKED ISSUE #14: Reserved keywords as column names cannot be used in generated where clause
Currently it is not possible to generate where clause in predicate pushdown if there are any column names as reserved keyword.

For example, `WHERE CONDITION < 5 ...`, this is going to fail currently.

### LINKED ISSUE #39: Preserve column quotes
The @3cham reported on #37 that we loose the quote information of the Exasol table column. 

We should preserve the column information in the connector. 

This is also similar issue to #14.

### LINKED ISSUE #84: Use sql-statement-builder
Use SQL Statement Builder to generate the internal SQL queries.

### PR DESCRIPTION
**Pull request by morazow**
Fixes #14 
Fixes #39 
Fixes #84

### CODE REVIEW

File: src/it/scala/com/exasol/spark/PredicatePushdownIT.scala [hunk 1]
```diff
@@ -1,91 +1,115 @@
...
-      .select("id", "city")
+  test("returns dataframe with not equal to filter") {
+    val df = getDataFrame().filter($"name" =!= "Germany").collect()
+    assert(df.map(r => r.getString(1)).contains("Germany") === false)
+  }
 
-    val result = df.collect().map(x => (x.getLong(0), x.getString(1))).toSet
-    assert(result.size === 1)
-    assert(result === Set((1, "Berlin")))
+  test("returns dataframe with greater than filter") {
```
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/it/scala/com/exasol/spark/PredicatePushdownIT.scala:25]: I think it's slightly more readable like this. If you agree, also change the other tests.

File: src/it/scala/com/exasol/spark/ReservedKeywordsIT.scala [hunk 2]
```diff
@@ -1,69 +1,50 @@
...
-
-  def createTable(): Unit =
+  override val tableName = s"$schema.TEST_TABLE"
+  override def createTable(): Unit =
     connectionManager.withExecute(
       Seq(
-        s"DROP SCHEMA IF EXISTS $SCHEMA CASCADE",
-        s"CREATE SCHEMA $SCHEMA",
-        s"""|CREATE OR REPLACE TABLE $SCHEMA.$TABLE (
+        s"DROP SCHEMA IF EXISTS $schema CASCADE",
```
Comment (jakobbraun) [inline src/it/scala/com/exasol/spark/ReservedKeywordsIT.scala:15]: use test-db-builder

File: src/it/scala/com/exasol/spark/TypesIT.scala [hunk 3]
```diff
@@ -1,22 +1,45 @@
...
-      .option("port", jdbcPort)
-      .option("query", s"SELECT * FROM $EXA_SCHEMA.$EXA_ALL_TYPES_TABLE")
-      .load()
+  private[this] val schema = "TYPES"
 
-    val schemaTest = df.schema
+  override val tableName = s"$schema.TEST_TABLE"
+  override def createTable(): Unit = {
+    val maxDecimal = " DECIMAL(" + getMaxPrecisionExasol() + "," + getMaxScaleExasol() + ")"
+    connectionManager.withExecute(
```
Comment (jakobbraun) [inline src/it/scala/com/exasol/spark/TypesIT.scala:14]: use test-db-builder

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 4]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
+        BooleanTerm.compare(column(attribute), "<>", getLiteral(value))
+      case GreaterThan(attribute, value) =>
+        BooleanTerm.gt(column(attribute), getLiteral(value))
+      case GreaterThanOrEqual(attribute, value) =>
+        BooleanTerm.ge(column(attribute), getLiteral(value))
+      case LessThan(attribute, value) =>
+        BooleanTerm.lt(column(attribute), getLiteral(value))
+      case LessThanOrEqual(attribute, value) =>
+        BooleanTerm.le(column(attribute), getLiteral(value))
+      // case IsNull(attribute) => stringLiteral(s"""("$attribute" IS NULL)""")
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:51]: remove commented out code

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 5]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
+      case StringContains(attribute, value) =>
+        BooleanTerm.like(column(attribute), stringLiteral(s"%$value%"))
+      case StringStartsWith(attribute, value) =>
+        BooleanTerm.like(column(attribute), stringLiteral(s"$value%"))
+      // case In(a, vs) => inExpr(a, vs, "IN", dataTypes)
+      // case Not(In(a, vs)) => inExpr(a, vs, "NOT IN", dataTypes)
+      case Not(notFilter) =>
+        filterToBooleanExpression(notFilter).map(BooleanTerm.not(_)).getOrElse(null)
+      case And(leftFilter, rightFilter) =>
+        val leftExpr = filterToBooleanExpression(leftFilter)
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:64]: extract method

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 6]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
+        val rightExpr = filterToBooleanExpression(rightFilter)
+        if (leftExpr.isDefined && rightExpr.isDefined) {
+          BooleanTerm.and(leftExpr.getOrElse(null), rightExpr.getOrElse(null))
+        } else {
+          null
+        }
+      case Or(leftFilter, rightFilter) =>
+        val leftExpr = filterToBooleanExpression(leftFilter)
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:72]: extract method

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 7]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
-    if (!leftOpt.isDefined) {
-      return None // scalastyle:ignore return
-    }
+  // scalastyle:off null
+  // Suppression is accepted since we have terminal conditions in the
+  // recursion.
+  @SuppressWarnings(Array("org.wartremover.warts.Recursion"))
+  def filterToBooleanExpression(filter: Filter): Option[BooleanExpression] =
+    Option(filter match {
+      case EqualTo(attribute, value) =>
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:39]: wow, what a cool syntax. A very nice alternative to have visitors all the time.

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 8]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
   /**
-   * Given a Spark source [[org.apache.spark.sql.sources.Filter]], create a
-   * Exasol SQL expression.
+   * Given a Spark source [[org.apache.spark.sql.sources.Filter]],
+   * creates an Exasol boolean expression.
    *
-   * Returns [[scala.None]] if an expression could not be created from the
-   * filter.
+   * @param filter a Spark source filter
+   * @return an Exasol boolean expression, [[scala.None]] is returned if
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:30]: is `scala.None` == `null`?

File: src/main/scala/com/exasol/spark/util/Filters.scala [hunk 9]
```diff
@@ -10,99 +14,85 @@ import org.apache.spark.sql.types._
...
+      case booleanValue: Boolean => booleanLiteral(booleanValue)
+      case stringValue: String   => stringLiteral(stringValue)
+      case byteValue: Byte       => integerLiteral(byteValue.toInt)
+      case shortValue: Short     => integerLiteral(shortValue.toInt)
+      case integerValue: Int     => integerLiteral(integerValue)
+      case longValue: Long       => longLiteral(longValue)
+      case floatValue: Float     => floatLiteral(floatValue)
+      case doubleValue: Double   => doubleLiteral(doubleValue)
+      // case bigDecimalValue: BigDecimal => BigDecimalLiteral(bigDecimalValue.underlying())
+      // case bigDecimalValue: java.math.BigDecimal => BigDecimalLiteral(bigDecimalValue)
```
Comment (jakobbraun) [inline src/main/scala/com/exasol/spark/util/Filters.scala:94]: remove commented out if possible

**Review by jakobbraun — CHANGES_REQUESTED** [review]

File: src/main/scala/com/exasol/spark/util/Filters.scala (hunk 7 above)
Comment (morazow) [reply src/main/scala/com/exasol/spark/util/Filters.scala:39]: Yes, that is beauty of the pattern matching. 

It helps a lot if the language supports it as a language construct.

File: src/main/scala/com/exasol/spark/util/Filters.scala (hunk 4 above)
Comment (morazow) [reply src/main/scala/com/exasol/spark/util/Filters.scala:51]: Done.
Added #89.

File: src/main/scala/com/exasol/spark/util/Filters.scala (hunk 8 above)
Comment (morazow) [reply src/main/scala/com/exasol/spark/util/Filters.scala:30]: No. It is the "undefined" part of the Optional, e.g, this is empty `Optional` from Java.

The option class has to subtypes, `Some[T]` (usually used as `Option[T]`) and `None`, `Option(null)` converted to `None` type.

File: src/it/scala/com/exasol/spark/PredicatePushdownIT.scala [hunk 10]
```diff
@@ -1,91 +1,115 @@
...
+    val df = getDataFrame().filter($"id" > 2).collect()
+    assert(df.map(r => r.getString(1)) === Seq("Portugal"))
```
[the remark this answers is not in the document]
Comment (morazow) [reply src/it/scala/com/exasol/spark/PredicatePushdownIT.scala:27]: Yes, it is tested in enricher class.

This is before sending the query to the Exasol. 

For example:

```
val df = spark.read
            .option("query", "SELECT * FROM people")
            .select("name", "surname")
            .filter($"id" > 10)
```

Should send the modified query to Exasol with column selection and where clauses:

```
SELECT "name", "surname" FROM people WHERE id > 10
```

File: src/it/scala/com/exasol/spark/BaseTableQueryIT.scala [hunk 11]
```diff
@@ -0,0 +1,35 @@
+package com.exasol.spark
+
+class BaseTableQueryIT extends AbstractTableQueryIT {
+
+  val schema = "TEST_SCHEMA"
+  override val tableName: String = s"$schema.TEST_TABLE"
+  override def createTable: Unit =
+    connectionManager.withExecute(
```
[the remark this answers is not in the document]
Comment (morazow) [reply src/it/scala/com/exasol/spark/BaseTableQueryIT.scala:8]: Clarified, added `exasol` prefix.

File: src/it/scala/com/exasol/spark/PredicatePushdownIT.scala (hunk 10 above)
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/it/scala/com/exasol/spark/PredicatePushdownIT.scala:27]: :+1:

File: src/it/scala/com/exasol/spark/BaseTableQueryIT.scala [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+      // scalastyle:off nonascii
+      Seq(
```
[the remark this answers is not in the document]
Comment (morazow) [reply src/it/scala/com/exasol/spark/BaseTableQueryIT.scala:10]: Yes, wanted to change but it cause some problems because of the default values (`identity` and `current_timestamp`).

TDDB expects them from user when inserting. I am going to address it in another ticket #90.

File: src/main/scala/com/exasol/spark/util/Filters.scala (hunk 8 above)
Comment (jakobbraun) [reply src/main/scala/com/exasol/spark/util/Filters.scala:30]: I see

File: src/it/scala/com/exasol/spark/BaseTableQueryIT.scala (hunk 12 above)
[the remark this answers is not in the document]
Comment (jakobbraun) [reply src/it/scala/com/exasol/spark/BaseTableQueryIT.scala:10]: ok

**Review by jakobbraun — APPROVED** [review]
