### PR TITLE
Check that the user provided host parameter value is an IP address

### LINKED ISSUE #43: Check Host Name
Problem:  subconnections do not work with domain name ("servername.domain.com"),  a IP is required (i.e. 169.100.168.100).

Solution:  On start, check "host" parameter with an regex for numbers, and if fail message user something readable

### PR DESCRIPTION
**Pull request by morazow**
This should help to fail-fast if users provide a domain name or non-ip value for the host parameter when using the Spark Exasol connector.

Fixes #43.

### CODE REVIEW

File: src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala [hunk 1]
```diff
@@ -51,14 +53,25 @@ final case class ExasolConfiguration(
 
 object ExasolConfiguration {
 
+  val IPv4_DIGITS: String = "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
```
Comment (3cham) [inline src/main/scala/com/exasol/spark/util/ExasolConfiguration.scala]: Since this rule accepts 192.168.2.**01** as valid address, I don't know if sub-connection could resolve this address (ping does). I'm currently having problem running it tests with my mac so I cannot verify it. Maybe could you please quickly check with our cluster @jpizagno ?
